Resources:
  TgBotUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TgBotUsers
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
